spring:
  application:
    name: demo
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liEvhkRDXBLv6Md0
            clientSecret: b4b3eae24cc4b269ee1f58e6edd24e51df83cc27

  datasource:
    url: jdbc:h2:file:./data/demo-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: name

